// THEMES
const DARK_THEME = Symbol("DARK_THEME");
const LIGHT_THEME = Symbol("LIGHT_THEME");

// EMAIL CONFIRMATION
const SAVE_EMAIL_CONFIRMATION = Symbol("SAVE_EMAIL_CONFIRMATION");
const RESET_EMAIL_CONFIRMATION = Symbol("RESET_EMAIL_CONFIRMATION");

// ADMIN CHECK
const EXIST_ADMIN = Symbol("EXIST_ADMIN");
const NOT_EXIST_ADMIN = Symbol("NOT_EXIST_ADMIN");

// AUTHENTICATION
const FORGET_USER = Symbol("FORGET_USER");
const REMEMBER_USER = Symbol("REMEMBER_USER");
const SAVE_SESSION = Symbol("SAVE_SESSION");
const CLEAN_SESSION = Symbol("CLEAN_SESSION");

// TESTIMONIALS
const DELETE_TESTIMONY = Symbol("DELETE_TESTIMONY");
const SET_TESTIMONIALS = Symbol("SET_TESTIMONIALS");
const SHOW_LOADING_TESTIMONIALS = Symbol("SHOW_LOADING_TESTIMONIALS");
const HIDE_LOADING_TESTIMONIALS = Symbol("HIDE_LOADING_TESTIMONIALS");

// ROLES
const ADD_ROLE = Symbol("ADD_ROLE");
const EDIT_ROLE = Symbol("EDIT_ROLE");
const DELETE_ROLE = Symbol("DELETE_ROLE");
const SET_ROLES = Symbol("SET_ROLES");
const SHOW_LOADING_ROLES = Symbol("SHOW_LOADING_ROLES");
const HIDE_LOADING_ROLES = Symbol("HIDE_LOADING_ROLES");

// USERS
const ADD_USER = Symbol("ADD_USER");
const DELETE_USER = Symbol("DELETE_USER");
const SET_USERS = Symbol("SET_USERS");
const SHOW_LOADING_USERS = Symbol("SHOW_LOADING_USERS");
const HIDE_LOADING_USERS = Symbol("HIDE_LOADING_USERS");

// DELETED_USERS
const ADD_DELETED_USER = Symbol("ADD_DELETED_USER");
const SET_DELETED_USERS = Symbol("SET_DELETED_USERS");
const SHOW_LOADING_DELETED_USERS = Symbol("SHOW_LOADING_DELETED_USERS");
const HIDE_LOADING_DELETED_USERS = Symbol("HIDE_LOADING_DELETED_USERS");

// SORT USERS BY
const SORT_USERS_BY_ASC_NAME = "sort-users-by-asc-name";
const SORT_USERS_BY_DESC_NAME = "sort-users-by-desc-name";
const SORT_USERS_BY_ASC_EMAIL = "sort-users-by-asc-email";
const SORT_USERS_BY_DESC_EMAIL = "sort-users-by-desc-email";
const SORT_USERS_BY_OLDEST_CREATED_AT = "sort-users-by-desc-createdAt";
const SORT_USERS_BY_MOST_RECENT_CREATED_AT = "sort-users-by-asc-createdAt";
const SORT_USERS_BY_OLDEST_UPDATED_AT = "sort-users-by-desc-updatedAt";
const SORT_USERS_BY_MOST_RECENT_UPDATED_AT = "sort-users-by-asc-updatedAt";

// SORT DELETED USERS BY
const SORT_DELETED_USERS_BY_ASC_NAME = "sort-deleted-users-by-asc-name";
const SORT_DELETED_USERS_BY_DESC_NAME = "sort-deleted-users-by-desc-name";
const SORT_DELETED_USERS_BY_ASC_EMAIL = "sort-deleted-users-by-asc-email";
const SORT_DELETED_USERS_BY_DESC_EMAIL = "sort-deleted-users-by-desc-email";
const SORT_DELETED_USERS_BY_OLDEST_DELETED_AT = "sort-deleted-users-by-asc-deletedAt";
const SORT_DELETED_USERS_BY_MOST_RECENT_DELETED_AT = "sort-deleted-users-by-desc-deletedAt";

// SEYTU PRODUCTS
const ADD_SEYTU_CATEGORY = Symbol("ADD_SEYTU_CATEGORY");
const EDIT_SEYTU_CATEGORY = Symbol("EDIT_SEYTU_CATEGORY");
const DELETE_SEYTU_CATEGORY = Symbol("DELETE_SEYTU_CATEGORY");
const DELETE_SEYTU_PRODUCT = Symbol("DELETE_SEYTU_PRODUCT");
const SET_SEYTU_ORDERS = Symbol("SET_SEYTU_ORDERS");
const SET_SEYTU_PRODUCTS = Symbol("SET_SEYTU_PRODUCTS");
const SET_SEYTU_CATEGORIES = Symbol("SET_SEYTU_CATEGORIES");
const CHANGE_SEYTU_ORDER_STATUS = Symbol("CHANGE_SEYTU_ORDER_STATUS");
const SHOW_LOADING_SEYTU_ORDERS = Symbol("SHOW_LOADING_SEYTU_ORDERS");
const SHOW_LOADING_SEYTU_PRODUCTS = Symbol("SHOW_LOADING_SEYTU_PRODUCTS");
const SHOW_LOADING_SEYTU_CATEGORIES = Symbol("SHOW_LOADING_SEYTU_CATEGORIES");
const HIDE_LOADING_SEYTU_ORDERS = Symbol("HIDE_LOADING_SEYTU_ORDERS");
const HIDE_LOADING_SEYTU_PRODUCTS = Symbol("HIDE_LOADING_SEYTU_PRODUCTS");
const HIDE_LOADING_SEYTU_CATEGORIES = Symbol("HIDE_LOADING_SEYTU_CATEGORIES");

// OMNILIFE PRODUCTS
const ADD_OMNILIFE_CATEGORY = Symbol("ADD_OMNILIFE_CATEGORY");
const EDIT_OMNILIFE_CATEGORY = Symbol("EDIT_OMNILIFE_CATEGORY");
const DELETE_OMNILIFE_CATEGORY = Symbol("DELETE_OMNILIFE_CATEGORY");
const DELETE_OMNILIFE_PRODUCT = Symbol("DELETE_OMNILIFE_PRODUCT");
const SET_OMNILIFE_ORDERS = Symbol("SET_OMNILIFE_ORDERS");
const SET_OMNILIFE_PRODUCTS = Symbol("SET_OMNILIFE_PRODUCTS");
const SET_OMNILIFE_CATEGORIES = Symbol("SET_OMNILIFE_CATEGORIES");
const CHANGE_OMNILIFE_ORDER_STATUS = Symbol("CHANGE_OMNILIFE_ORDER_STATUS");
const SHOW_LOADING_OMNILIFE_ORDERS = Symbol("SHOW_LOADING_OMNILIFE_ORDERS");
const SHOW_LOADING_OMNILIFE_PRODUCTS = Symbol("SHOW_LOADING_OMNILIFE_PRODUCTS");
const SHOW_LOADING_OMNILIFE_CATEGORIES = Symbol("SHOW_LOADING_OMNILIFE_CATEGORIES");
const HIDE_LOADING_OMNILIFE_ORDERS = Symbol("HIDE_LOADING_OMNILIFE_ORDERS")
const HIDE_LOADING_OMNILIFE_PRODUCTS = Symbol("HIDE_LOADING_OMNILIFE_PRODUCTS");
const HIDE_LOADING_OMNILIFE_CATEGORIES = Symbol("HIDE_LOADING_OMNILIFE_CATEGORIES");

// SORT SEYTU ORDERS BY
const SORT_SEYTU_ORDERS_BY_ASC_CLIENT_NAME = "sort-seytu-orders-by-asc-clientName";
const SORT_SEYTU_ORDERS_BY_DESC_CLIENT_NAME = "sort-seytu-orders-by-desc-clientName";
const SORT_SEYTU_ORDERS_BY_ASC_PRODUCT_NAME = "sort-seytu-orders-by-asc-productName";
const SORT_SEYTU_ORDERS_BY_DESC_PRODUCT_NAME = "sort-seytu-orders-by-desc-productName";
const SORT_SEYTU_ORDERS_BY_MINOR_QUANTITY = "sort-seytu-orders-by-minor-quantity";
const SORT_SEYTU_ORDERS_BY_HIGHEST_QUANTITY = "sort-seytu-orders-by-highest-quantity";
const SORT_SEYTU_ORDERS_BY_OLDEST_CREATED_AT = "sort-seytu-orders-by-asc-createdAt";
const SORT_SEYTU_ORDERS_BY_MOST_RECENT_CREATED_AT = "sort-seytu-orders-by-desc-createdAt"

// SORT SEYTU PRODUCTS BY
const SORT_SEYTU_PRODUCTS_BY_ASC_NAME = "sort-seytu-products-by-asc-name";
const SORT_SEYTU_PRODUCTS_BY_DESC_NAME = "sort-seytu-products-by-desc-name";
const SORT_SEYTU_PRODUCTS_BY_HIGHEST_STOCK = "sort-seytu-products-by-highest-stock";
const SORT_SEYTU_PRODUCTS_BY_MINOR_STOCK = "sort-seytu-products-by-minor-stock";
const SORT_SEYTU_PRODUCTS_BY_OLDEST_CREATED_AT = "sort-seytu-products-by-asc-createdAt"
const SORT_SEYTU_PRODUCTS_BY_MOST_RECENT_CREATED_AT = "sort-seytu-products-by-desc-createdAt"
const SORT_SEYTU_PRODUCTS_BY_MOST_RECENT_UPDATED_AT = "sort-seytu-products-by-desc-updatedAt"
const SORT_SEYTU_PRODUCTS_BY_OLDEST_UPDATED_AT = "sort-seytu-products-by-asc-updatedAt";

// SORT OMNILIFE ORDERS BY
const SORT_OMNILIFE_ORDERS_BY_ASC_CLIENT_NAME = "sort-omnilife-orders-by-asc-clientName";
const SORT_OMNILIFE_ORDERS_BY_DESC_CLIENT_NAME = "sort-omnilife-orders-by-desc-clientName";
const SORT_OMNILIFE_ORDERS_BY_ASC_PRODUCT_NAME = "sort-omnilife-orders-by-asc-productName";
const SORT_OMNILIFE_ORDERS_BY_DESC_PRODUCT_NAME = "sort-omnilife-orders-by-desc-productName";
const SORT_OMNILIFE_ORDERS_BY_MINOR_QUANTITY = "sort-omnilife-orders-by-minor-quantity";
const SORT_OMNILIFE_ORDERS_BY_HIGHEST_QUANTITY = "sort-omnilife-orders-by-highest-quantity";
const SORT_OMNILIFE_ORDERS_BY_MOST_RECENT_CREATED_AT = "sort-omnilife-orders-by-desc-createdAt"
const SORT_OMNILIFE_ORDERS_BY_OLDEST_CREATED_AT = "sort-omnilife-orders-by-asc-createdAt"

// SORT OMNILIFE PRODUCTS BY
const SORT_OMNILIFE_PRODUCTS_BY_ASC_NAME = "sort-omnilife-products-by-asc-name";
const SORT_OMNILIFE_PRODUCTS_BY_DESC_NAME = "sort-omnilife-products-by-desc-name";
const SORT_OMNILIFE_PRODUCTS_BY_HIGHEST_STOCK = "sort-omnilife-products-by-highest-stock"
const SORT_OMNILIFE_PRODUCTS_BY_MINOR_STOCK = "sort-omnilife-products-by-minor-stock";
const SORT_OMNILIFE_PRODUCTS_BY_MOST_RECENT_CREATED_AT =
  "sort-omnilife-products-by-desc-createdAt";
const SORT_OMNILIFE_PRODUCTS_BY_OLDEST_CREATED_AT = "sort-omnilife-products-by-asc-createdAt"
const SORT_OMNILIFE_PRODUCTS_BY_MOST_RECENT_UPDATED_AT =
  "sort-omnilife-products-by-desc-updatedAt";
const SORT_OMNILIFE_PRODUCTS_BY_OLDEST_UPDATED_AT = "sort-omnilife-products-by-asc-updatedAt"

// SAVE FILTERS IN USERS TABLE
const SAVE_USERS_FILTERS = Symbol("SAVE_USERS_FILTERS");

// SAVE FILTERS IN DELETED USERS TABLE
const SAVE_DELETED_USERS_FILTERS = Symbol("SAVE_DELETED_USERS_FILTERS");

// SAVE FILTERS IN SEYTU PRODUCTS
const SAVE_SEYTU_EXTRA_FILTERS = Symbol("SAVE_SEYTU_EXTRA_FILTERS");

// SAVE FILTERS IN OMNILIFE PRODUCTS
const SAVE_OMNILIFE_EXTRA_FILTERS = Symbol("SAVE_OMNILIFE_EXTRA_FILTERS");

export {
  // Temas
  DARK_THEME,
  LIGHT_THEME,

  // Verificación de usuario administrador
  EXIST_ADMIN,
  NOT_EXIST_ADMIN,

  // Confirmación de correo electrónico
  SAVE_EMAIL_CONFIRMATION,
  RESET_EMAIL_CONFIRMATION,

  // Autenticación
  FORGET_USER,
  REMEMBER_USER,
  SAVE_SESSION,
  CLEAN_SESSION,

  // Roles de usuarios
  ADD_ROLE,
  EDIT_ROLE,
  DELETE_ROLE,
  SET_ROLES,
  SHOW_LOADING_ROLES,
  HIDE_LOADING_ROLES,
  
  // Usuarios
  ADD_USER,
  DELETE_USER,
  SET_USERS,
  SHOW_LOADING_USERS,
  HIDE_LOADING_USERS,
  
  // Usuarios eliminados
  ADD_DELETED_USER,
  SET_DELETED_USERS,
  SHOW_LOADING_DELETED_USERS,
  HIDE_LOADING_DELETED_USERS,

  // Productos Seytú
  ADD_SEYTU_CATEGORY,
  EDIT_SEYTU_CATEGORY,
  DELETE_SEYTU_CATEGORY,
  DELETE_SEYTU_PRODUCT,
  SET_SEYTU_ORDERS,
  SET_SEYTU_PRODUCTS,
  SET_SEYTU_CATEGORIES,
  CHANGE_SEYTU_ORDER_STATUS,
  SHOW_LOADING_SEYTU_PRODUCTS,
  SHOW_LOADING_SEYTU_ORDERS,
  SHOW_LOADING_SEYTU_CATEGORIES,
  HIDE_LOADING_SEYTU_PRODUCTS,
  HIDE_LOADING_SEYTU_ORDERS,
  HIDE_LOADING_SEYTU_CATEGORIES,

  // Productos Omnilife
  ADD_OMNILIFE_CATEGORY,
  EDIT_OMNILIFE_CATEGORY,
  DELETE_OMNILIFE_CATEGORY,
  DELETE_OMNILIFE_PRODUCT,
  SET_OMNILIFE_ORDERS,
  SET_OMNILIFE_PRODUCTS,
  SET_OMNILIFE_CATEGORIES,
  CHANGE_OMNILIFE_ORDER_STATUS,
  SHOW_LOADING_OMNILIFE_PRODUCTS,
  SHOW_LOADING_OMNILIFE_ORDERS,
  SHOW_LOADING_OMNILIFE_CATEGORIES,
  HIDE_LOADING_OMNILIFE_PRODUCTS,
  HIDE_LOADING_OMNILIFE_ORDERS,
  HIDE_LOADING_OMNILIFE_CATEGORIES,

  // Testimonios
  DELETE_TESTIMONY,
  SET_TESTIMONIALS,
  SHOW_LOADING_TESTIMONIALS,
  HIDE_LOADING_TESTIMONIALS,

  // Ordenar usuarios por
  SORT_USERS_BY_ASC_NAME,
  SORT_USERS_BY_DESC_NAME,
  SORT_USERS_BY_ASC_EMAIL,
  SORT_USERS_BY_DESC_EMAIL,
  SORT_USERS_BY_OLDEST_CREATED_AT,
  SORT_USERS_BY_MOST_RECENT_CREATED_AT,
  SORT_USERS_BY_OLDEST_UPDATED_AT,
  SORT_USERS_BY_MOST_RECENT_UPDATED_AT,

  // Ordenar usuarios eliminados por
  SORT_DELETED_USERS_BY_ASC_NAME,
  SORT_DELETED_USERS_BY_DESC_NAME,
  SORT_DELETED_USERS_BY_ASC_EMAIL,
  SORT_DELETED_USERS_BY_DESC_EMAIL,
  SORT_DELETED_USERS_BY_MOST_RECENT_DELETED_AT,
  SORT_DELETED_USERS_BY_OLDEST_DELETED_AT,

  // Ordenar pedidos de productos Seytú por
  SORT_SEYTU_ORDERS_BY_ASC_CLIENT_NAME,
  SORT_SEYTU_ORDERS_BY_DESC_CLIENT_NAME,
  SORT_SEYTU_ORDERS_BY_ASC_PRODUCT_NAME,
  SORT_SEYTU_ORDERS_BY_DESC_PRODUCT_NAME,
  SORT_SEYTU_ORDERS_BY_MINOR_QUANTITY,
  SORT_SEYTU_ORDERS_BY_HIGHEST_QUANTITY,
  SORT_SEYTU_ORDERS_BY_MOST_RECENT_CREATED_AT,
  SORT_SEYTU_ORDERS_BY_OLDEST_CREATED_AT,

  // Ordenar productos Seytú por
  SORT_SEYTU_PRODUCTS_BY_ASC_NAME,
  SORT_SEYTU_PRODUCTS_BY_DESC_NAME,
  SORT_SEYTU_PRODUCTS_BY_HIGHEST_STOCK,
  SORT_SEYTU_PRODUCTS_BY_MINOR_STOCK,
  SORT_SEYTU_PRODUCTS_BY_MOST_RECENT_CREATED_AT,
  SORT_SEYTU_PRODUCTS_BY_OLDEST_CREATED_AT,
  SORT_SEYTU_PRODUCTS_BY_MOST_RECENT_UPDATED_AT,
  SORT_SEYTU_PRODUCTS_BY_OLDEST_UPDATED_AT,

  // Ordenar pedidos de productos Omnilife por
  SORT_OMNILIFE_ORDERS_BY_ASC_CLIENT_NAME,
  SORT_OMNILIFE_ORDERS_BY_DESC_CLIENT_NAME,
  SORT_OMNILIFE_ORDERS_BY_ASC_PRODUCT_NAME,
  SORT_OMNILIFE_ORDERS_BY_DESC_PRODUCT_NAME,
  SORT_OMNILIFE_ORDERS_BY_MINOR_QUANTITY,
  SORT_OMNILIFE_ORDERS_BY_HIGHEST_QUANTITY,
  SORT_OMNILIFE_ORDERS_BY_MOST_RECENT_CREATED_AT,
  SORT_OMNILIFE_ORDERS_BY_OLDEST_CREATED_AT,

  // Ordenar productos Omnilife por
  SORT_OMNILIFE_PRODUCTS_BY_ASC_NAME,
  SORT_OMNILIFE_PRODUCTS_BY_DESC_NAME,
  SORT_OMNILIFE_PRODUCTS_BY_HIGHEST_STOCK,
  SORT_OMNILIFE_PRODUCTS_BY_MINOR_STOCK,
  SORT_OMNILIFE_PRODUCTS_BY_MOST_RECENT_CREATED_AT,
  SORT_OMNILIFE_PRODUCTS_BY_OLDEST_CREATED_AT,
  SORT_OMNILIFE_PRODUCTS_BY_MOST_RECENT_UPDATED_AT,
  SORT_OMNILIFE_PRODUCTS_BY_OLDEST_UPDATED_AT,

  // Guardar filtros en tablas de usuarios existentes y eliminados
  SAVE_USERS_FILTERS,
  SAVE_DELETED_USERS_FILTERS,

  // Guardar filtros de los productos Seytú y Omnilife
  SAVE_SEYTU_EXTRA_FILTERS,
  SAVE_OMNILIFE_EXTRA_FILTERS,
};
